drop table registration if exists;
create table registration (
        id bigint generated by default as identity (start with 1),
        mobile_no varchar(255) not null,
        reference_num bigint not null,
        referred_by varchar(255),
        registered_time timestamp not null,
        primary key (id)
);
alter table registration add constraint uk_mobile_no unique (mobile_no);